server:
  port: 3003

spring:
  application:
    name: ORDER-SERVICE-CS2

eureka:
  client:
    register-with-client: true
    fetch-registry: true
    service-url:
      default:zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost